### PR TITLE
Setup a react application

### PR DESCRIPTION
**Pull request by fatmahussein**
- Set up linter config
- Used the correct gitflow
- Create a react app

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @fatmahussein 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive branch name and you currently have linter errors on this pr 👍🏿  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by fatmahussein** [comment]
Hi @prolajumokeoni 

Thank you

**Review by skyv26 — APPROVED** [review]
## Hi @fatmahussein, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## STATUS: APPROVED 🟢 




## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 
- Correct `.github/workflows` for linters ✅ 

## Optional suggestions

- **Please follow the convention of making good branch names for your feature branch which reflect some meaning and tell something about or related to the project your branch is just a `feature` which seems like it does contain some feature, but what kind of feature is unclear. So instead you can use a branch name something called `setup_branch` or `feature_setup_math_magician` or `feature/math-magician-setup` which actually tells a meaningful branch functionality.**

- **Please try to write a more descriptive PR description, which does contain good information about your branch features or tell something about what you did in the particular branch or implemented. Have a good descriptive PR description can make any person more understand about what you did and what a person can expect from you without going deep into the project directories.**

### PR Description Comparison
<table>
<tr>
<th>Good PR Description</th>
<th>Your PR Description</th>
</tr>
<tr>
<td>

Screenshot from 2023-08-15 11-54-38

</td>
<td>

image

</td>
</tr>
</table>
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   @skyv26
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   linkedin-skyv2022
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   @vrma_aakash
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   @skybrel
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   @skybrel
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fatmahussein** [comment]
Thanks @skyv26

**Pull request merged**
